AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
Metrics/ClassLength:
  Exclude:
    - 'test/**/*'
Metrics/MethodLength:
  Exclude:
    - 'test/**/*'

Lint/AssignmentInCondition:
  Exclude:
    - 'lib/prosopite/mysql_query.rb'
